title: Continuum Hypnosis
email: julia@continuum-hypnosis.co.uk
description: >-
  Julia Lewis is a lecturer and tutor for the London College of Clinical
  Hypnosis. Supporting others as they discover the benefits that hypnosis
  has to offer.
  A volunteer Clinical Hypnotherapist for Anxiety UK.
baseurl: "" # the subpath of your site, e.g. /blog
url: "continuum-hypnosis.com"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

gems: ['kramdown']

exclude:
  - Gemfile
  - Gemfile.lock
  - images/*.acorn
  - config.ru
  - vendor
  - Procfile
  - Rakefile
